import React from 'react';
import Head from 'next/head';
import { Layout, theme, ConfigProvider } from 'antd';

import Table from '@components/atoms/table';
import MenuSider from '@components/organisms/menuSider';
import 'antd/dist/reset.css';

const { Header, Content, Footer } = Layout;

export default function Home() {
  const {
    token: { colorBgContainer },
  } = theme.useToken();

  const defaultTheme = {
    "token": {
      "colorPrimary": "#4a86f6",
      "colorInfo": "#4a86f6",
      "borderRadius": 4,
      "borderRadiusLG": 4,
      "borderRadiusXS": 4
    }
  }

  return (
    <>
      <Head>
        <title>Component Module</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ConfigProvider theme={defaultTheme}>
        <Layout hasSider>
          <MenuSider />
          <Layout
            className="site-layout"
            style={{ marginLeft: 200, minHeight: '100vh' }}
          >
            <Header style={{ padding: 0, background: colorBgContainer }} />
            <Content style={{ margin: '24px 16px 0', overflow: 'initial' }}>
              <div style={{ padding: 24, textAlign: 'center', background: colorBgContainer }}>
                <Table />
              </div>
            </Content>
            <Footer style={{ textAlign: 'center' }}>Ant Design ©2023 Created by Ant UED</Footer>
          </Layout>
        </Layout>
      </ConfigProvider>
    </>
  )
}
