import {
  AppstoreOutlined,
  BarChartOutlined,
  CloudOutlined,
  ShopOutlined,
  TeamOutlined,
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
} from '@ant-design/icons';
import { ConfigProvider, Layout, Menu, theme } from 'antd';

import Head from 'next/head';
import type { MenuProps } from 'antd';
import React from 'react';
import dynamic from 'next/dynamic';

const Table = dynamic(() => import('remote/table'), {
  ssr: false,
});

const { Header, Content, Footer, Sider } = Layout;


const items: MenuProps['items'] = [
  UserOutlined,
  VideoCameraOutlined,
  UploadOutlined,
  BarChartOutlined,
  CloudOutlined,
  AppstoreOutlined,
  TeamOutlined,
  ShopOutlined,
].map((icon, index) => ({
  key: String(index + 1),
  icon: React.createElement(icon),
  label: `nav ${index + 1}`,
}));

export default function Home() {
  const {
    token: { colorBgContainer },
  } = theme.useToken();

  const defaultTheme = {
    'token': {
      'colorPrimary': '#ff7c82',
      'colorInfo': '#ff7c82',
      'borderRadius': 12,
      'borderRadiusLG': 16,
      'borderRadiusXS': 8
    }
  }

  const data: any[] = [
    {
      key: '1',
      name: 'TP - Jane',
      age: 32,
      address: 'New York No. 1 Lake Park',
      tags: ['nice', 'developer'],
    },
    {
      key: '2',
      name: 'TP - Morroc',
      age: 42,
      address: 'London No. 1 Lake Park',
      tags: ['loser'],
    },
    {
      key: '3',
      name: 'TP - Lodash',
      age: 32,
      address: 'Sydney No. 1 Lake Park',
      tags: ['cool', 'teacher'],
    },
  ];

  return (
    <>
      <Head>
        <title>Training Center Module</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ConfigProvider theme={defaultTheme}>
        <Layout hasSider>
          <Sider
            style={{
              overflow: 'auto',
              height: '100vh',
              position: 'fixed',
              left: 0,
              top: 0,
              bottom: 0,
              background: colorBgContainer
            }}
          >
            <div style={{ height: 32, margin: 16, background: defaultTheme.token.colorPrimary }} />
            <Menu mode="inline" defaultSelectedKeys={['0']} items={items} />
          </Sider>
          <Layout className="site-layout" style={{ marginLeft: 200, minHeight: '100vh' }}>
            <Header style={{ padding: 0, background: colorBgContainer }} />
            <Content style={{ margin: '24px 16px 0', overflow: 'initial' }}>
              <div style={{ padding: 24, textAlign: 'center', background: colorBgContainer }}>
                <Table data={data} theme={defaultTheme} />
                <p>long content</p>
                {
                  // indicates very long content
                  Array.from({ length: 100 }, (_, index) => (
                    <React.Fragment key={index}>
                      {index % 20 === 0 && index ? 'more' : '...'}
                      <br />
                    </React.Fragment>
                  ))
                }
              </div>
            </Content>
            <Footer style={{ textAlign: 'center' }}>Ant Design ©2023 Created by Ant UED</Footer>
          </Layout>
        </Layout>
      </ConfigProvider>
    </>
  )
}
